spring:
  application:
    name: jwt-server-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
jwt:
  secret:
    access: e8SiLayEF5HIyzUVKWSJohoJnOSPEfDepe+Z9ZGi3YeuZ+UgpMRIlvCI72TSnz962+PU0DELpUJYHuptAgUkEA==
    refresh: zZbAyzBUA9ZMjbh/V+FdwsEyAXqQlKwQbkMH4jP69NjFhvSHz1zCd4bAJze1sKYg17Y6hKjvPhAq8/K3gFtk1g==