server:
  port: 9000
spring:
  application:
    name: authorization-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
base:
  url:
    redirect: ${REDIRECT_URL:http://127.0.0.1:8765/}