spring:
  application:
    name: avatar-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVICE:http://localhost:9002}