spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,resource.read
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_SERVICE:http://localhost:9000}
            authorization-uri: ${AUTHORIZATION_SERVICE:http://localhost:9000}/oauth2/authorize
            token-uri: ${AUTHORIZATION_SERVICE:http://localhost:9000}/oauth2/token
base:
  url:
    rest:
      template:
        jwt : ${JWT_SERVER_SERVICE_URL:http://localhost:8765}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE