spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/resource
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
base:
  url:
    rest:
      template:
        jwt : ${JWT_SERVER_SERVICE_URL:http://localhost:8765}
security:
   oauth2:
     client:
       registration:
         gateway:
           provider: spring
           client-id: gateway
           client-secret: secret
           authorization-grant-type: authorization_code
           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
           scope: openid,resource.read
       provider:
         spring:
           issuer-uri: http://localhost:9000