spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
base:
  url:
    rest:
      template: ${USER_SERVICE_URL:http://localhost:8765}