--liquibase formatted sql

--changeset igor:1
CREATE TABLE messages
(
    id  INT8 GENERATED BY DEFAULT AS IDENTITY,
    data_create_message TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE '-03:00') NOT NULL,
    content VARCHAR(255) NOT NULL,
    chat_id INT8 NOT NULL ,
    sender_user_id INT8 NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:2
CREATE TABLE users
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    avatar_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:3
CREATE TABLE chats
(
    id  INT8 GENERATED BY DEFAULT AS IDENTITY,
    chat_name VARCHAR(255),
    PRIMARY KEY (id)
);

--changeset igor:4
CREATE TABLE chats_users
(
    chat_id INT8 NOT NULL,
    user_id INT8 NOT NULL,
    PRIMARY KEY (chat_id, user_id)
);