spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000