server:
  port: 8761
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}