--liquibase formatted sql

--changeset igor:1

CREATE TABLE users
(
    id        INT8 GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    avatar_id VARCHAR(255) NOT NULL,
    role      VARCHAR(32)  NOT NULL DEFAULT 'USER',
    PRIMARY KEY (id)
);
