server:
  port: 8083

topic:
  name: t.message

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5432}/${POSTGRES_DB_NAME:chats_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9093}
    consumer:
      auto-offset-reset: earliest
      group-id: "default"


