server:
  port: 8083

topic:
  name: t.message

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chats_db
    username: postgres
    password: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: validate
    show-sql: true



